package etudiant;

import gestionVoeu.CandidatureDetail;
import gestionVoeu.EtatVoeu;
import javax.swing.JOptionPane;

/**
 *
 * @author Yvan
 */
public class EtudiantChoice extends javax.swing.JPanel {

    /**
     * Creates new form EtudiantChoiceAdd
     */
    public EtudiantChoice() {
        initComponents();
    }
    
    public void makeChoice(CandidatureDetail voeu, EtatVoeu choix){
        
    }
    
    public void ajouterVoeu(){
        
    }
    
    public void afficherTexteOut(String text){
        textOut.append(text);
        textOut.append("\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootTabPane = new javax.swing.JTabbedPane();
        seeChoices = new javax.swing.JScrollPane();
        createVoeu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rectoratList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        universityList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        formationList = new javax.swing.JList();
        addChoice = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textOut = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(900, 650));
        setMinimumSize(new java.awt.Dimension(900, 650));
        setPreferredSize(new java.awt.Dimension(900, 650));

        rootTabPane.setMaximumSize(new java.awt.Dimension(900, 650));
        rootTabPane.setMinimumSize(new java.awt.Dimension(900, 650));
        rootTabPane.addTab("Voir ses voeux", seeChoices);

        rectoratList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rectoratList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(rectoratList);

        universityList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        universityList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(universityList);

        formationList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        formationList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(formationList);

        addChoice.setText("Ajouter le voeu");
        addChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createVoeuLayout = new javax.swing.GroupLayout(createVoeu);
        createVoeu.setLayout(createVoeuLayout);
        createVoeuLayout.setHorizontalGroup(
            createVoeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createVoeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createVoeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createVoeuLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createVoeuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addChoice)))
                .addContainerGap())
        );
        createVoeuLayout.setVerticalGroup(
            createVoeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createVoeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createVoeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(addChoice)
                .addContainerGap())
        );

        rootTabPane.addTab("Ajouter un voeu", createVoeu);

        textOut.setColumns(20);
        textOut.setRows(5);
        jScrollPane4.setViewportView(textOut);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        rootTabPane.addTab("tab3", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChoiceActionPerformed
        String rectorat = (String) rectoratList.getSelectedValue();
        String university = (String) universityList.getSelectedValue();
        String formation = (String) formationList.getSelectedValue();
        JOptionPane.showMessageDialog(null, "Rectorat: "+ rectorat + " - Université: " + university + " - Formation: " + formation);
    }//GEN-LAST:event_addChoiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChoice;
    private javax.swing.JPanel createVoeu;
    private javax.swing.JList formationList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList rectoratList;
    private javax.swing.JTabbedPane rootTabPane;
    private javax.swing.JScrollPane seeChoices;
    private javax.swing.JTextArea textOut;
    private javax.swing.JList universityList;
    // End of variables declaration//GEN-END:variables
}
