package etudiant;

import gestionVoeu.EtatVoeu;
import gestionVoeu.VoeuxDetail;

/**
 *
 * @author Yvan
 */
public class VoeuPanel extends javax.swing.JPanel {
    
    private VoeuxDetail voeuAffiche;
    private EtudiantChoice etudiantChoice;

    /**
     * Creates new form VoeuPanel
     */
    public VoeuPanel(VoeuxDetail voeu, EtudiantChoice parent) {
        this.voeuAffiche = voeu;
        this.etudiantChoice = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voeuDesc = new javax.swing.JLabel();
        nonDefButton = new javax.swing.JToggleButton();
        ouiDefButton = new javax.swing.JToggleButton();
        ouiMaisButton = new javax.swing.JToggleButton();
        nonMaisButton = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(640, 36));
        setMinimumSize(new java.awt.Dimension(640, 36));

        voeuDesc.setText("voeuDesc");

        nonDefButton.setText("Non définitif");
        nonDefButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nonDefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonDefButtonActionPerformed(evt);
            }
        });

        ouiDefButton.setText("Oui Définitif");
        ouiDefButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ouiDefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiDefButtonActionPerformed(evt);
            }
        });

        ouiMaisButton.setText("Oui mais");
        ouiMaisButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ouiMaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiMaisButtonActionPerformed(evt);
            }
        });

        nonMaisButton.setText("Non mais");
        nonMaisButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nonMaisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonMaisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voeuDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ouiDefButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ouiMaisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nonMaisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nonDefButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voeuDesc)
                    .addComponent(nonDefButton)
                    .addComponent(ouiDefButton)
                    .addComponent(nonMaisButton)
                    .addComponent(ouiMaisButton))
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ouiDefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiDefButtonActionPerformed
        this.etudiantChoice.makeChoice(voeuAffiche, EtatVoeu.OUI_DEFINITIF);
    }//GEN-LAST:event_ouiDefButtonActionPerformed

    private void ouiMaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiMaisButtonActionPerformed
        this.etudiantChoice.makeChoice(voeuAffiche, EtatVoeu.OUI_MAIS);
    }//GEN-LAST:event_ouiMaisButtonActionPerformed

    private void nonMaisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonMaisButtonActionPerformed
        this.etudiantChoice.makeChoice(voeuAffiche, EtatVoeu.NON_MAIS);
    }//GEN-LAST:event_nonMaisButtonActionPerformed

    private void nonDefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonDefButtonActionPerformed
        this.etudiantChoice.makeChoice(voeuAffiche, EtatVoeu.NON_DEFINITIF);
    }//GEN-LAST:event_nonDefButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton nonDefButton;
    private javax.swing.JToggleButton nonMaisButton;
    private javax.swing.JToggleButton ouiDefButton;
    private javax.swing.JToggleButton ouiMaisButton;
    private javax.swing.JLabel voeuDesc;
    // End of variables declaration//GEN-END:variables
}
