package universiteclient;

import gestionVoeu.CandidatureDetail;
import gestionVoeu.Quartile;

/**
 *
 * @author Yvan
 */
public class CandidaturePanel extends javax.swing.JPanel {

    private UniversiteChoice parent;
    private CandidatureDetail cd;
    
    /**
     * Creates new form CandidaturePanel
     * @param cd Candidature à afficher
     * @param parent fenêtre parente
     */
    public CandidaturePanel(CandidatureDetail cd, UniversiteChoice parent) {
        this.parent = parent;
        this.cd = cd;
        initComponents();
        this.nomLabel.setText(cd.voeuxDetail.etu.nom);
        this.prenomLabel.setText(cd.voeuxDetail.etu.prenom);
        this.adresseLabel.setText(cd.voeuxDetail.etu.adresse);
        this.universiteLabel.setText(cd.voeuxDetail.etu.universite);
        this.licenseLabel.setText(cd.voeuxDetail.etu.license);
        this.s1quartProgress.setValue(this.quartileToInt(cd.voeuxDetail.etu.listeSeum[0].quartile));
        this.s2quartProgress.setValue(this.quartileToInt(cd.voeuxDetail.etu.listeSeum[1].quartile));
        this.s3quartProgress.setValue(this.quartileToInt(cd.voeuxDetail.etu.listeSeum[2].quartile));
        this.s4quartProgress.setValue(this.quartileToInt(cd.voeuxDetail.etu.listeSeum[3].quartile));
        this.s5quartProgress.setValue(this.quartileToInt(cd.voeuxDetail.etu.listeSeum[4].quartile));
        this.s6quartProgress.setValue(this.quartileToInt(cd.voeuxDetail.etu.listeSeum[5].quartile));
        this.s1noteLabel.setText(Float.toString(cd.voeuxDetail.etu.listeSeum[0].moyenne));
        this.s2noteLabel.setText(Float.toString(cd.voeuxDetail.etu.listeSeum[1].moyenne));
        this.s3noteLabel.setText(Float.toString(cd.voeuxDetail.etu.listeSeum[2].moyenne));
        this.s4noteLabel.setText(Float.toString(cd.voeuxDetail.etu.listeSeum[3].moyenne));
        this.s5noteLabel.setText(Float.toString(cd.voeuxDetail.etu.listeSeum[4].moyenne));
        this.s6noteLabel.setText(Float.toString(cd.voeuxDetail.etu.listeSeum[5].moyenne));
        this.s1moyenLabel.setText(cd.voeuxDetail.etu.listeSeum[0].moyenObtention.toString());
        this.s2moyenLabel.setText(cd.voeuxDetail.etu.listeSeum[1].moyenObtention.toString());
        this.s3moyenLabel.setText(cd.voeuxDetail.etu.listeSeum[2].moyenObtention.toString());
        this.s4moyenLabel.setText(cd.voeuxDetail.etu.listeSeum[3].moyenObtention.toString());
        this.s5moyenLabel.setText(cd.voeuxDetail.etu.listeSeum[4].moyenObtention.toString());
        this.s6moyenLabel.setText(cd.voeuxDetail.etu.listeSeum[5].moyenObtention.toString());
        
        this.setVisible(true);
    }
    
    private int quartileToInt(Quartile quart){
        switch(quart.value()){
            case Quartile._PREMIER_QUART: return 100;
            case Quartile._DEUXIEME_QUART: return 75;
            case Quartile._TROISIEME_QUART: return 50;
            case Quartile._QUATRIEME_QUART: return 25;
            default: return 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prenomLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adresseLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        universiteLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        licenseLabel = new javax.swing.JLabel();
        s1quartProgress = new javax.swing.JProgressBar();
        s3quartProgress = new javax.swing.JProgressBar();
        s5quartProgress = new javax.swing.JProgressBar();
        s2quartProgress = new javax.swing.JProgressBar();
        s4quartProgress = new javax.swing.JProgressBar();
        s6quartProgress = new javax.swing.JProgressBar();
        s3noteLabel = new javax.swing.JLabel();
        s5noteLabel = new javax.swing.JLabel();
        s2noteLabel = new javax.swing.JLabel();
        s4noteLabel = new javax.swing.JLabel();
        s6noteLabel = new javax.swing.JLabel();
        s1noteLabel = new javax.swing.JLabel();
        s1moyenLabel = new javax.swing.JLabel();
        s2moyenLabel = new javax.swing.JLabel();
        s3moyenLabel = new javax.swing.JLabel();
        s5moyenLabel = new javax.swing.JLabel();
        s4moyenLabel = new javax.swing.JLabel();
        s6moyenLabel = new javax.swing.JLabel();
        accepterButton = new javax.swing.JButton();
        enAttenteButton = new javax.swing.JButton();
        refuserButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(920, 120));
        setMinimumSize(new java.awt.Dimension(920, 120));
        setPreferredSize(new java.awt.Dimension(920, 120));

        jLabel1.setText("Nom:");

        nomLabel.setText("jLabel2");
        nomLabel.setToolTipText("");

        jLabel3.setText("Prénom:");

        prenomLabel.setText("jLabel4");

        jLabel5.setText("Adresse: ");

        adresseLabel.setText("jLabel6");

        jLabel7.setText("Université: ");

        universiteLabel.setText("jLabel8");

        jLabel9.setText("License: ");

        licenseLabel.setText("jLabel10");

        s3quartProgress.setForeground(new java.awt.Color(51, 70, 255));

        s5quartProgress.setForeground(new java.awt.Color(51, 30, 122));

        s4quartProgress.setForeground(new java.awt.Color(51, 70, 255));

        s6quartProgress.setForeground(new java.awt.Color(51, 30, 122));

        s3noteLabel.setText("jLabel12");

        s5noteLabel.setText("jLabel13");

        s2noteLabel.setText("jLabel14");

        s4noteLabel.setText("jLabel15");

        s6noteLabel.setText("jLabel16");

        s1noteLabel.setText("jLabel17");

        s1moyenLabel.setText("jLabel18");

        s2moyenLabel.setText("jLabel19");

        s3moyenLabel.setText("jLabel20");

        s5moyenLabel.setText("jLabel21");

        s4moyenLabel.setText("jLabel22");

        s6moyenLabel.setText("jLabel23");

        accepterButton.setText("Accepter");

        enAttenteButton.setText("En attente");

        refuserButton.setText("Refuser");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prenomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(adresseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(universiteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(licenseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(s3quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s5quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(s5noteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(s5moyenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(s6quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(s1noteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(s3noteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s1moyenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(s2quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s3moyenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(s4quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s2noteLabel)
                                .addGap(18, 18, 18)
                                .addComponent(s2moyenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s4noteLabel)
                                .addGap(18, 18, 18)
                                .addComponent(s4moyenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s6noteLabel)
                                .addGap(18, 18, 18)
                                .addComponent(s6moyenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accepterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(enAttenteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refuserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nomLabel))
                    .addComponent(s1quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s1noteLabel)
                        .addComponent(s1moyenLabel))
                    .addComponent(s2quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s2noteLabel)
                        .addComponent(s2moyenLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(prenomLabel))
                    .addComponent(s3quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s3noteLabel)
                        .addComponent(s3moyenLabel))
                    .addComponent(s4quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s4noteLabel)
                        .addComponent(s4moyenLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s6noteLabel)
                        .addComponent(s6moyenLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(adresseLabel))
                            .addComponent(s5quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(s5noteLabel)
                                .addComponent(s5moyenLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(universiteLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(licenseLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(accepterButton)
                                .addComponent(enAttenteButton)
                                .addComponent(refuserButton))))
                    .addComponent(s6quartProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accepterButton;
    private javax.swing.JLabel adresseLabel;
    private javax.swing.JButton enAttenteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel licenseLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JLabel prenomLabel;
    private javax.swing.JButton refuserButton;
    private javax.swing.JLabel s1moyenLabel;
    private javax.swing.JLabel s1noteLabel;
    private javax.swing.JProgressBar s1quartProgress;
    private javax.swing.JLabel s2moyenLabel;
    private javax.swing.JLabel s2noteLabel;
    private javax.swing.JProgressBar s2quartProgress;
    private javax.swing.JLabel s3moyenLabel;
    private javax.swing.JLabel s3noteLabel;
    private javax.swing.JProgressBar s3quartProgress;
    private javax.swing.JLabel s4moyenLabel;
    private javax.swing.JLabel s4noteLabel;
    private javax.swing.JProgressBar s4quartProgress;
    private javax.swing.JLabel s5moyenLabel;
    private javax.swing.JLabel s5noteLabel;
    private javax.swing.JProgressBar s5quartProgress;
    private javax.swing.JLabel s6moyenLabel;
    private javax.swing.JLabel s6noteLabel;
    private javax.swing.JProgressBar s6quartProgress;
    private javax.swing.JLabel universiteLabel;
    // End of variables declaration//GEN-END:variables
}
