package universiteclient;

import gestionVoeu.DiplomeDetail;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import tools.IDValue;
import tools.IDValueCustomRenderer;

/**
 *
 * @author Yvan
 */
public class UniversiteChoice extends javax.swing.JFrame {

    /**
     * Creates new form UniversiteChoice
     */
    public UniversiteChoice() {
        initComponents();
        
        //initialiser les éléments
        this.universiteLibelle.setText(UniversiteClient.getInstance().getUniversiteLibelle());
        this.rectoratLibelle.setText(UniversiteClient.getInstance().getRectoratLibelle());
        
        this.comboFormation.setRenderer(new IDValueCustomRenderer());
        DefaultComboBoxModel<IDValue> modelFormation = new DefaultComboBoxModel<>();
        for(DiplomeDetail form : UniversiteClient.getInstance().getFormationsList()){
            modelFormation.addElement(new IDValue(Integer.toString(form.id), form.libelle));
        }
        comboFormation.setModel(modelFormation);
        
        //ouvrir la fenêtre
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    class ComboFormationListener implements ListSelectionListener {
        
        private String lastMember = null;

        @Override
        public void valueChanged(ListSelectionEvent lse) {
            if(!lse.getValueIsAdjusting()){
                String str = ((IDValue) comboFormation.getModel().getElementAt(lse.getFirstIndex())).ID;
                String str2 = ((IDValue) comboFormation.getModel().getElementAt(lse.getLastIndex())).ID;
                if(str == null ? lastMember != null : !str.equals(lastMember)){
                    lastMember = str;
                } else {
                    lastMember = str2;
                }
                //utiliser lastMember
                seeVoeux.removeAll();
                
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        universiteLibelle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rectoratLibelle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboFormation = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        nombreOuiDefLibelle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        seeVoeux = new javax.swing.JPanel();
        buttonClore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Université: ");

        universiteLibelle.setText("jLabel2");

        jLabel3.setText("Rectorat: ");

        rectoratLibelle.setText("jLabel4");

        jLabel5.setText("Formation: ");

        jLabel6.setText("Nombre de Oui Défnitif dans la formation: ");

        nombreOuiDefLibelle.setText("jLabel7");

        javax.swing.GroupLayout seeVoeuxLayout = new javax.swing.GroupLayout(seeVoeux);
        seeVoeux.setLayout(seeVoeuxLayout);
        seeVoeuxLayout.setHorizontalGroup(
            seeVoeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
        );
        seeVoeuxLayout.setVerticalGroup(
            seeVoeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(seeVoeux);

        buttonClore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonClore.setForeground(new java.awt.Color(255, 0, 0));
        buttonClore.setText("CLORE LES INSCRIPTIONS !!!!!!!!!!!!!!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonClore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboFormation, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(universiteLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(rectoratLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreOuiDefLibelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(universiteLibelle)
                    .addComponent(jLabel3)
                    .addComponent(rectoratLibelle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboFormation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(nombreOuiDefLibelle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClore)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClore;
    private javax.swing.JComboBox comboFormation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreOuiDefLibelle;
    private javax.swing.JLabel rectoratLibelle;
    private javax.swing.JPanel seeVoeux;
    private javax.swing.JLabel universiteLibelle;
    // End of variables declaration//GEN-END:variables
}
